# Generated by Django 3.0.4 on 2020-03-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialCircle',
            new_name='Group',
        ),
    ]
