# Generated by Django 3.0.4 on 2020-03-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200322_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user',
        ),
    ]
