# Generated by Django 3.0.4 on 2020-03-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200329_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
    ]
