# Generated by Django 3.0.4 on 2020-04-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_profilephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePhoto',
        ),
    ]
