# Generated by Django 3.0.4 on 2020-04-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_profilephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='workers',
        ),
    ]
