# Generated by Django 3.0.4 on 2020-04-01 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_platform_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Platform'),
        ),
    ]
