# Generated by Django 3.0.4 on 2020-04-01 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_profile_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='workers',
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Position'),
        ),
    ]
