# Generated by Django 3.0.4 on 2020-04-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200401_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='key',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
