# Generated by Django 3.0.4 on 2020-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200401_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='key',
            field=models.CharField(default='', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='key',
            field=models.CharField(default='', max_length=36, unique=True),
        ),
    ]
