# Generated by Django 3.0.4 on 2020-04-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200401_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='key',
            field=models.CharField(default='', max_length=36),
        ),
    ]
