# Generated by Django 3.0.4 on 2020-04-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200401_1944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Platform',
            new_name='PlatformCompany',
        ),
    ]
