# Generated by Django 3.0.4 on 2020-04-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200401_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
