# Generated by Django 3.0.4 on 2020-04-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200401_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='company',
        ),
        migrations.CreateModel(
            name='PositionCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Position')),
            ],
        ),
    ]
