# Generated by Django 3.0.4 on 2020-04-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200401_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Command',
        ),
    ]
