# Generated by Django 3.0.4 on 2020-04-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200402_1829'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='Groups',
        ),
        migrations.AlterModelTable(
            name='platformcompany',
            table='Platforms in company',
        ),
        migrations.AlterModelTable(
            name='platforms',
            table='Platforms',
        ),
        migrations.AlterModelTable(
            name='position',
            table='Positions',
        ),
        migrations.AlterModelTable(
            name='positioncompany',
            table='Positions in company',
        ),
    ]
