# Generated by Django 3.0.4 on 2020-04-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200402_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='answers',
            field=models.ManyToManyField(to='main.Answers'),
        ),
        migrations.AddField(
            model_name='poll',
            name='questions',
            field=models.ManyToManyField(to='main.Questions'),
        ),
    ]
