# Generated by Django 3.0.4 on 2020-04-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200405_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='respondent',
        ),
    ]
