# Generated by Django 3.0.4 on 2020-04-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_poll_respondent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='assessed',
            new_name='initiator',
        ),
    ]
