# Generated by Django 3.0.4 on 2020-04-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200406_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='start_date',
        ),
    ]
