# Generated by Django 3.0.4 on 2020-04-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200412_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioncompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company'),
        ),
    ]
