# Generated by Django 3.0.4 on 2020-04-15 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20200415_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='answers',
        ),
        migrations.AddField(
            model_name='answers',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Poll'),
        ),
    ]
