# Generated by Django 3.0.4 on 2020-04-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20200415_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='count_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='name_poll',
            field=models.CharField(default='', max_length=50),
        ),
    ]
