# Generated by Django 3.0.4 on 2020-04-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20200415_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_poll',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Poll'),
        ),
    ]
