# Generated by Django 3.0.4 on 2020-04-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_profile_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rating',
            new_name='answers_sum',
        ),
        migrations.AddField(
            model_name='profile',
            name='count_answers',
            field=models.IntegerField(default=0),
        ),
    ]
