# Generated by Django 3.0.4 on 2020-04-15 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20200415_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
            options={
                'db_table': 'Profile photo',
            },
        ),
    ]
