# Generated by Django 3.0.4 on 2020-04-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
