# Generated by Django 3.0.4 on 2020-04-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20200415_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
