# Generated by Django 3.0.4 on 2020-04-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20200418_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='template_type',
            field=models.IntegerField(choices=[(0, 'default'), (1, 'company'), (2, 'team')], default=2),
        ),
    ]
