# Generated by Django 3.0.4 on 2020-04-25 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_poll_template_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='poll',
            table='Poll',
        ),
    ]
