# Generated by Django 3.0.4 on 2020-04-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20200425_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access',
            field=models.IntegerField(choices=[(0, 'user'), (1, 'hr'), (2, 'admin')], default=0),
        ),
    ]
