# Generated by Django 3.0.4 on 2020-04-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_profile_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access',
            field=models.IntegerField(choices=[(0, 'user'), (1, 'hr'), (2, 'admin'), (3, 'company_owner')], default=0),
        ),
    ]
