# Generated by Django 3.0.4 on 2020-04-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_companyadmins_companyhr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='access',
        ),
    ]
