# Generated by Django 3.0.4 on 2020-04-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_remove_profile_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='question',
            new_name='text',
        ),
        migrations.AddField(
            model_name='questions',
            name='type',
            field=models.CharField(choices=[('text', 0), ('radio', 1), ('range', 2)], default='range', max_length=10),
        ),
    ]
