# Generated by Django 3.0.4 on 2020-04-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20200429_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatespoll',
            name='template_type',
        ),
        migrations.AddField(
            model_name='templatespoll',
            name='type',
            field=models.CharField(choices=[('default', 0), ('company', 1), ('team', 2)], default='default', max_length=10),
        ),
    ]
