# Generated by Django 3.0.4 on 2020-04-29 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0058_auto_20200429_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='count_answers',
        ),
        migrations.AddField(
            model_name='poll',
            name='users_completed_poll',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='poll',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
