# Generated by Django 3.0.4 on 2020-04-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20200429_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='users_completed_poll',
            new_name='respondents',
        ),
        migrations.AddField(
            model_name='poll',
            name='count_completed_polls',
            field=models.IntegerField(default=0),
        ),
    ]
