# Generated by Django 3.0.4 on 2020-04-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20200429_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='count_completed_polls',
        ),
    ]
