# Generated by Django 3.0.4 on 2020-04-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_remove_poll_count_completed_polls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer',
        ),
        migrations.AddField(
            model_name='answers',
            name='count_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answers',
            name='sum_answer',
            field=models.IntegerField(default=0),
        ),
    ]
