# Generated by Django 3.0.4 on 2020-04-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20200429_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Questions'),
        ),
    ]
