# Generated by Django 3.0.4 on 2020-05-01 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20200429_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField(default=0)),
                ('max', models.IntegerField(default=100)),
                ('step', models.IntegerField(default=10)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Questions')),
            ],
            options={
                'db_table': 'Questions settings',
            },
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=30)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Settings')),
            ],
            options={
                'db_table': 'Answer choice',
            },
        ),
    ]
