# Generated by Django 3.0.4 on 2020-05-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_answerchoice_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerchoice',
            name='settings',
        ),
        migrations.AddField(
            model_name='settings',
            name='answer_choice',
            field=models.ManyToManyField(to='main.AnswerChoice'),
        ),
    ]
