# Generated by Django 3.0.4 on 2020-05-02 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20200501_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerchoice',
            old_name='answer',
            new_name='value',
        ),
    ]
