# Generated by Django 3.0.4 on 2020-05-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20200502_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchoice',
            name='weight',
            field=models.IntegerField(default=10),
        ),
    ]
