# Generated by Django 3.0.4 on 2020-05-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_answerchoice_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='key',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='key',
            field=models.CharField(default='', max_length=36),
        ),
    ]
