# Generated by Django 3.0.4 on 2020-05-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_notifications_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
