# Generated by Django 3.0.4 on 2020-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_poll_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer_choice',
            field=models.ManyToManyField(to='main.AnswerChoice'),
        ),
    ]
