# Generated by Django 3.0.4 on 2020-05-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_questions_answer_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answer_choice',
        ),
    ]
