# Generated by Django 3.0.4 on 2020-05-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_remove_questions_answer_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchoice',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
