# Generated by Django 3.0.4 on 2020-05-08 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_answerchoice_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='choices',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.AnswerChoice'),
        ),
    ]
