# Generated by Django 3.0.4 on 2020-05-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_answers_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='text_answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.CharField(choices=[('small_text', 0), ('radio', 1), ('range', 2), ('checkbox', 3), ('big_text', 4)], default='range', max_length=10),
        ),
    ]
