# Generated by Django 3.0.4 on 2020-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_auto_20200509_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='choices',
        ),
        migrations.AddField(
            model_name='answers',
            name='choices',
            field=models.ManyToManyField(to='main.AnswerChoice'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='text_answer',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
