# Generated by Django 3.0.4 on 2020-05-09 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_auto_20200509_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(default='', max_length=500)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Answers')),
            ],
            options={
                'db_table': 'Text answer',
            },
        ),
    ]
