# Generated by Django 3.0.4 on 2020-05-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0078_textanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='text_answer',
        ),
    ]
