# Generated by Django 3.0.4 on 2020-05-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_auto_20200509_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatespoll',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
