# Generated by Django 3.0.4 on 2020-05-14 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_templatespoll_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
