# Generated by Django 3.0.4 on 2020-06-27 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0085_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
    ]
