# Generated by Django 3.0.4 on 2020-07-07 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_profile_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EvaluationMessage',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answerchoice',
            name='count',
        ),
        migrations.RemoveField(
            model_name='answerchoice',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='count_answers',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='sum_answer',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='type',
        ),
        migrations.AddField(
            model_name='answers',
            name='range_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Poll'),
        ),
        migrations.AddField(
            model_name='settings',
            name='type',
            field=models.CharField(choices=[('small_text', 0), ('radio', 1), ('range', 2), ('checkbox', 3)], default='range', max_length=10),
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='value',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='answers',
            name='choices',
        ),
        migrations.AddField(
            model_name='answers',
            name='choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.AnswerChoice'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='step',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='OpenAnswer',
        ),
        migrations.DeleteModel(
            name='OpenQuestions',
        ),
        migrations.DeleteModel(
            name='TextAnswer',
        ),
    ]
