# Generated by Django 3.0.4 on 2020-07-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0088_auto_20200707_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerchoice',
            old_name='value',
            new_name='text',
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ManyToManyField(to='main.Poll')),
                ('profile', models.ManyToManyField(to='main.Profile')),
            ],
            options={
                'db_table': 'Draft',
            },
        ),
    ]
