# Generated by Django 3.0.4 on 2020-07-08 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_auto_20200708_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='profile',
        ),
        migrations.AddField(
            model_name='draft',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
