# Generated by Django 3.0.4 on 2020-07-08 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_auto_20200708_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
