# Generated by Django 3.0.4 on 2020-07-09 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_auto_20200708_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
    ]
