# Generated by Django 3.0.4 on 2020-07-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_auto_20200709_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='answers_sum',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='count_answers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_poll',
        ),
        migrations.AddField(
            model_name='profile',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
