# Generated by Django 3.0.4 on 2020-07-09 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_auto_20200709_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
            options={
                'db_table': 'BirthDate',
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
