# Generated by Django 3.0.4 on 2020-07-09 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_auto_20200709_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthdate',
            old_name='date',
            new_name='birthday',
        ),
    ]
