# Generated by Django 3.0.4 on 2020-07-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_auto_20200709_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_is_validate',
            field=models.BooleanField(default=False),
        ),
    ]
