# Generated by Django 3.0.4 on 2020-07-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_auto_20200713_1240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyHR',
            new_name='Moderator',
        ),
        migrations.RenameModel(
            old_name='CompanyAdmins',
            new_name='SurveyWizard',
        ),
        migrations.AlterModelTable(
            name='moderator',
            table='Moderator',
        ),
        migrations.AlterModelTable(
            name='surveywizard',
            table='SurveyWizard',
        ),
    ]
