# Generated by Django 3.0.4 on 2020-07-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_auto_20200713_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fullname',
        ),
    ]
