# Generated by Django 3.0.4 on 2020-07-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_auto_20200719_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformcompany',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='positioncompany',
            name='position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AddField(
            model_name='platformcompany',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='positioncompany',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Platforms',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
