# Generated by Django 3.0.4 on 2020-07-19 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_auto_20200719_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PlatformCompany'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PositionCompany'),
        ),
    ]
