# Generated by Django 3.0.4 on 2020-07-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_auto_20200719_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='redirect',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
