# Generated by Django 3.0.4 on 2020-07-20 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0102_auto_20200720_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='notifications',
            name='about',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='notifications',
            name='from_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_profile', to='main.Profile'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='on_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_profile', to='main.Profile'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('my_poll', 0), ('invite', 1), ('alien_poll', 2)], default='my_poll', max_length=10),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(to='main.Group'),
        ),
    ]
