# Generated by Django 3.0.4 on 2020-07-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0103_auto_20200720_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('my_poll', 0), ('invite_command', 1), ('invite_company', 2), ('alien_poll', 3)], default='my_poll', max_length=15),
        ),
    ]
