# Generated by Django 3.0.4 on 2020-07-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0104_auto_20200720_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='about',
        ),
    ]
