# Generated by Django 3.0.4 on 2020-07-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_notifications_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='count_passed',
            field=models.IntegerField(default=0),
        ),
    ]
