# Generated by Django 3.0.4 on 2020-07-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_poll_count_passed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='data',
            new_name='date',
        ),
    ]
