# Generated by Django 3.0.4 on 2020-07-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='complited',
            field=models.BooleanField(default=False),
        ),
    ]
