# Generated by Django 3.0.4 on 2020-07-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_poll_complited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='complited',
            new_name='completed',
        ),
    ]
