# Generated by Django 3.0.4 on 2020-07-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_auto_20200721_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='completed',
        ),
        migrations.AddField(
            model_name='notifications',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
