# Generated by Django 3.0.4 on 2020-07-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_auto_20200721_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='platform',
        ),
        migrations.AddField(
            model_name='profile',
            name='platform',
            field=models.ManyToManyField(to='main.PlatformCompany'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ManyToManyField(to='main.PositionCompany'),
        ),
    ]
