# Generated by Django 3.0.4 on 2020-07-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0113_auto_20200721_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='platform',
            new_name='platforms',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='position',
            new_name='positions',
        ),
    ]
