# Generated by Django 3.0.4 on 2020-07-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_auto_20200723_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='photo_hex',
            field=models.BigIntegerField(null=True),
        ),
    ]
