# Generated by Django 3.0.4 on 2020-07-28 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0117_auto_20200728_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
