# Generated by Django 3.0.4 on 2020-07-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0118_auto_20200728_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='profile',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
