# Generated by Django 3.0.4 on 2020-07-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_auto_20200729_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilephoto',
            name='photo_hex',
        ),
    ]
