# Generated by Django 3.0.8 on 2020-07-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_remove_profilephoto_photo_hex'),
        ('main', '0099_remove_profile_fullname'),
    ]

    operations = [
    ]
