# Generated by Django 3.0.4 on 2020-07-31 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0122_auto_20200731_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='respondents',
        ),
        migrations.CreateModel(
            name='RespondentPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_viewed', models.BooleanField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Poll')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
            options={
                'db_table': 'RespondentPoll',
            },
        ),
    ]
