# Generated by Django 3.0.4 on 2020-07-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_auto_20200731_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='key',
        ),
    ]
