# Generated by Django 3.0.4 on 2020-07-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0124_remove_poll_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NeedPassPoll',
        ),
    ]
