# Generated by Django 3.0.4 on 2020-08-01 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_delete_needpasspoll'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RespondentPoll',
            new_name='NeedPassPoll',
        ),
    ]
