# Generated by Django 3.0.4 on 2020-08-01 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_auto_20200801_1106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeedPassPoll',
            new_name='RespondentPoll',
        ),
    ]
