# Generated by Django 3.0.4 on 2020-08-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0127_auto_20200801_1123'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RespondentPoll',
            new_name='NeedPassPoll',
        ),
    ]
