# Generated by Django 3.0.4 on 2020-08-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_auto_20200803_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatespoll',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
