# Generated by Django 3.0.4 on 2020-08-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0133_templatespoll_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='needpasspoll',
            name='is_rendered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='needpasspoll',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
