# Generated by Django 3.0.8 on 2020-08-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0135_testtable'),
        ('main', '0122_auto_20200730_1622'),
    ]

    operations = [
    ]
