# Generated by Django 3.0.4 on 2020-08-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0135_testtable'),
        ('main', '0099_remove_profile_fullname'),
    ]

    operations = [
    ]
