# Generated by Django 3.0.8 on 2020-08-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0136_merge_20200805_1830'),
        ('main', '0136_merge_20200806_1342'),
    ]

    operations = [
    ]
