# Generated by Django 3.0.8 on 2020-08-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0137_merge_20200806_1350'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
