# Generated by Django 3.0.4 on 2020-08-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0137_group_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
