# Generated by Django 3.0.4 on 2020-08-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0138_questions_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
