# Generated by Django 3.0.8 on 2020-08-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0138_auto_20200806_1817'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
        migrations.AlterModelTable(
            name='profilephoto',
            table=None,
        ),
    ]
