# Generated by Django 3.0.8 on 2020-08-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0139_auto_20200806_1834'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profilephoto',
            table='Profile photo',
        ),
    ]
