# Generated by Django 3.0.4 on 2020-08-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0139_poll_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
