# Generated by Django 3.0.4 on 2020-08-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0140_poll_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='needpasspoll',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
