# Generated by Django 3.0.8 on 2020-08-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0140_auto_20200806_1838'),
        ('main', '0137_group_company'),
    ]

    operations = [
    ]
