# Generated by Django 3.0.4 on 2020-08-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0141_needpasspoll_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['ordinal_number']},
        ),
        migrations.AddField(
            model_name='questions',
            name='ordinal_number',
            field=models.IntegerField(default=0),
        ),
    ]
