# Generated by Django 3.0.4 on 2020-08-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0143_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitations',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
        ),
    ]
