# Generated by Django 3.0.4 on 2020-08-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0145_invitations_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(0, 'team'), (1, 'company')], default='team', max_length=15)),
                ('invitation_group_id', models.IntegerField(default=0)),
                ('date', models.DateField(null=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Profile')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
            options={
                'db_table': 'Invitation',
            },
        ),
        migrations.DeleteModel(
            name='Invitations',
        ),
    ]
