# Generated by Django 3.0.4 on 2020-08-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0146_auto_20200818_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
