# Generated by Django 3.0.4 on 2020-08-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0147_delete_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/media/images/'),
        ),
    ]
