# Generated by Django 3.0.4 on 2020-08-19 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0149_auto_20200819_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='new_template',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TemplatesPoll'),
        ),
    ]
