# Generated by Django 3.0.4 on 2020-08-20 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0150_poll_new_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'OpenQuestion',
            },
        ),
        migrations.RemoveField(
            model_name='answers',
            name='range_number',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='text',
        ),
        migrations.AddField(
            model_name='answers',
            name='range_overage',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='answers',
            name='choices',
        ),
        migrations.AlterField(
            model_name='answers',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Poll'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('answer_choice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.AnswerChoice')),
            ],
            options={
                'db_table': 'Choice',
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='open_answer',
            field=models.ManyToManyField(to='main.OpenQuestion'),
        ),
        migrations.AddField(
            model_name='answers',
            name='choices',
            field=models.ManyToManyField(to='main.Choice'),
        ),
    ]
