# Generated by Django 3.0.8 on 2020-08-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0141_merge_20200812_1535'),
        ('main', '0150_poll_new_template'),
    ]

    operations = [
    ]
