# Generated by Django 3.0.4 on 2020-08-20 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0152_auto_20200820_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Poll'),
        ),
    ]
