# Generated by Django 3.0.4 on 2020-08-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0153_auto_20200820_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='range_overage',
            new_name='range_sum',
        ),
    ]
