# Generated by Django 3.0.4 on 2020-08-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0154_auto_20200820_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdpoll',
            name='is_rendered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createdpoll',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
