# Generated by Django 3.0.8 on 2020-08-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0155_auto_20200825_1759'),
        ('main', '0151_merge_20200819_1956'),
    ]

    operations = [
    ]
