# Generated by Django 3.0.4 on 2020-08-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0155_auto_20200825_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_rendered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
