# Generated by Django 3.0.4 on 2020-08-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0156_auto_20200827_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='from_id_group',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='start_from',
            field=models.CharField(default='polls', max_length=10),
        ),
    ]
