# Generated by Django 3.0.4 on 2020-08-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0157_auto_20200829_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_from',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
