# Generated by Django 3.0.4 on 2020-08-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0159_auto_20200830_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatespoll',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
