# Generated by Django 3.0.4 on 2020-08-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0161_rangeanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtable',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
