# Generated by Django 3.0.4 on 2020-08-31 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0162_testtable_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='from_id_group',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='start_from',
        ),
    ]
