# Generated by Django 3.0.4 on 2020-09-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0164_auto_20200831_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchoice',
            name='text',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='text',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='platformcompany',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='poll',
            name='name_poll',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='positioncompany',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=models.CharField(max_length=150),
        ),
    ]
