# Generated by Django 3.0.8 on 2020-09-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0156_merge_20200826_2024'),
        ('main', '0164_auto_20200831_1836'),
    ]

    operations = [
    ]
