# Generated by Django 3.0.4 on 2020-09-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0165_merge_20200902_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='type',
            field=models.CharField(choices=[('small_text', 0), ('radio', 1), ('range', 2), ('checkbox', 3)], default='range', max_length=20),
        ),
    ]
