# Generated by Django 3.0.4 on 2020-09-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0165_auto_20200916_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatespoll',
            name='name_poll',
            field=models.CharField(max_length=150),
        ),
    ]
