# Generated by Django 3.0.4 on 2020-09-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0166_auto_20200916_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
