# Generated by Django 3.0.4 on 2020-09-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0166_auto_20200904_0226'),
        ('main', '0167_delete_testtable'),
    ]

    operations = [
    ]
